### ISSUE TITLE
PHP Parse error: 

### ISSUE THREAD

**Issue by ropelletier** [sqonk/mysql-sync#1]
PHP Parse error:  syntax error, unexpected ':', expecting ')' in /opt/mysql-sync/vendor/sqonk/mysql-sync/sync.php on line 50

**Comment by sqonk** [comment]
Thanks for the heads up. I had a number of uncommitted changes, which I have now pushed. The current dev-master branch works is working on my end. Could you please test on your end and confirm if it has also been resolved on your end. If it has I'll do a new release.
