### ISSUE TITLE
Added Port

### ISSUE THREAD

**Issue by LuckyLukeCH** [sqonk/mysql-sync#2]
Hello @Sqonk,

Very nice tool, thank you!

Added the port to the connections:
```
$source = new mysqli($config->source->host, $config->source->user, $config->source->password, $config->source->database, $config->source->port);

$dest = new mysqli($config->dest->host, $config->dest->user, $config->dest->password, $config->dest->database, $config->dest->port);
```

Regards from Switzerland,
LuckyLuke

**Comment by sqonk** [comment]
Hey there, 
I missed it didn't I! :-D

Thanks very much for dropping me a line and letting me know. I'll push a fix up promptly. 👍

**Comment by sqonk** [comment]
Thanks @LuckyLukeCH I have pushed a commit up. 
Once I have had a chance to do a real world test I'll do a release.

**Comment by LuckyLukeCH** [comment]
Hello @sqonk,

Thank you very much! Your tool works great and is a big help for me!

Regards from Switzerland
LuckyLuke
