### ISSUE TITLE
Where can I set the mysql-sync?

### ISSUE THREAD

**Issue by BorghettiG** [sqonk/mysql-sync#3]
I need to syncronize two database between two wordpress project in two localhost by github. How can I proceed, can you give me the steps?
Thank you

**Comment by sqonk** [comment]
Your best bet is to use method one as described on the ReadMe.md

_Firstly - backup your destination database, if what you are syncing to is precious on any level..._
- From your project folder, or where ever you are going to run it from, do `**composer require sqonk/mysql-sync**`.
- Create the JSON file as per the format on the ReadMe, or copy the sample file in the conf folder. Save this file to the same place. In this examples lets assume you call the config file **prod.sync.json**
- Put all the correct details in for both source and destination databases into this config file.
- Run the sync with **vendor/bin/mysql-sync prod.sync.json**

Once you run it this will do a dry run, which will examine what changes there are between the two.

If there are any changes it will show you new tables to be added, tables to be dropped and tables to be modified. 

If you are satisfied all looks to be correct it will give you 3 options:
- [D]eploy: execute the changes displayed directly to the destination database.
- [s]ave: save the SQL commands directly to a diff file for you to copy into your preferred SQL client and execute manually. 
- [c]ancel: cancel the synchronisation and exit.
